version: '2.0'
services:
  github-cd:
    image: blockpilld/github-cd:1.3
    env:
      - GITHUB_REPO=https://github.com/blockpill/nextjs-starter.git
      - INSTALL_COMMAND=yarn install --frozen-lockfile 
      - BUILD_COMMAND=yarn build 
      - START_COMMAND=yarn start 
      - ADMIN_USERNAME=test
      - ADMIN_PASSWORD=testing
      - WEBHOOK_SECRET=webhooksecret
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
      - port: 8080
        to:
          - global: true
      - port: 9000
        to:
          - global: true
profiles:
  compute:
    github-cd:
      resources:
        cpu:
          units: '1'
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        github-cd:
          denom: uakt
          amount: 3000
deployment:
  github-cd:
    westcoast:
      profile: github-cd
      count: 1